/**
 * My modified version of the original code generated by v0.
 */
import Link from "next/link"
import Image from 'next/image'
import { Button } from "@/components/ui/button"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"

export function Store() {
  return (
    <div key="1" className="h-screen mx-auto px-4 sm:px-6 lg:px-8 py-6 bg-gray-900 text-white">
      <header className="flex justify-between items-center mb-6 bg-gray-700 p-3 rounded-lg shadow-md">
        <Link href="#">
          <h1 className="text-2xl font-bold tracking-wider flex items-center">
            <svg
              className=" mr-2 h-6 w-6"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="M12 20.94c1.5 0 2.75 1.06 4 1.06 3 0 6-8 6-12.22A4.91 4.91 0 0 0 17 5c-2.22 0-4 1.44-5 2-1-.56-2.78-2-5-2a4.9 4.9 0 0 0-5 4.78C2 14 5 22 8 22c1.25 0 2.5-1.06 4-1.06Z" />
              <path d="M10 2c1 .5 2 2 2 5" />
            </svg>
            FreshPick
          </h1>
        </Link>
        <nav>
          <Button variant="ghost">
            <Link aria-label="Shopping Cart" href="#">
              <svg
                className=" text-white h-6 w-6 hover:text-black"
                fill="none"
                height="24"
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                viewBox="0 0 24 24"
                width="24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <circle cx="8" cy="21" r="1" />
                <circle cx="19" cy="21" r="1" />
                <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
              </svg>
            </Link>
          </Button>
        </nav>
      </header>
      <main className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 text-black">
        <div className="card rounded overflow-hidden shadow-lg bg-gray-800">
          <Image
            alt="Apple Image"
            height="200"
            src="/products/apple.jpg"
            style={{
              aspectRatio: "200/200",
              objectFit: "cover",
              width: "100%",
            }}
            width="200"
          />
          <div className="p-4">
            <h2 className="font-bold text-xl mb-2 text-white">Apple</h2>
            <p className="text-gray-300 text-base mb-2">
              <span className="line-through text-red-500 mr-2">$49.99</span>
              $39.99
            </p>
            <div className="flex items-center gap-4">
              <Button
                className="bg-gradient-to-r from-green-400 to-blue-500 hover:from-green-500 hover:to-blue-600 text-white"
                variant="default"
              >
                Add to Cart
              </Button>
              <Select defaultValue="1">
                <SelectTrigger className="w-16">
                  <SelectValue placeholder="Qty" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="1">1</SelectItem>
                  <SelectItem value="2">2</SelectItem>
                  <SelectItem value="3">3</SelectItem>
                  <SelectItem value="4">4</SelectItem>
                  <SelectItem value="5">5</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </div>
        <div className="card rounded overflow-hidden shadow-lg bg-gray-800">
          <Image
            alt="Banana Image"
            height="200"
            src="/products/banana.jpg"
            style={{
              aspectRatio: "200/200",
              objectFit: "cover",
              width: "100%",
            }}
            width="200"
          />
          <div className="p-4">
            <h2 className="font-bold text-xl mb-2 text-white">Banana</h2>
            <p className="text-gray-300 text-base mb-2">$59.99</p>
            <div className="flex items-center gap-4">
              <Button
                className="bg-gradient-to-r from-green-400 to-blue-500 hover:from-green-500 hover:to-blue-600 text-white"
                variant="default"
              >
                Add to Cart
              </Button>
              <Select defaultValue="1">
                <SelectTrigger className="w-16">
                  <SelectValue placeholder="Qty" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="1">1</SelectItem>
                  <SelectItem value="2">2</SelectItem>
                  <SelectItem value="3">3</SelectItem>
                  <SelectItem value="4">4</SelectItem>
                  <SelectItem value="5">5</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </div>
        <div className="card rounded overflow-hidden shadow-lg bg-gray-800">
          <Image
            alt="Cherry Image"
            height="200"
            src="/products/cherry.jpg"
            style={{
              aspectRatio: "200/200",
              objectFit: "cover",
              width: "100%",
            }}
            width="200"
          />
          <div className="p-4">
            <h2 className="font-bold text-xl mb-2 text-white">Cherry</h2>
            <p className="text-gray-300 text-base mb-2">
              <span className="line-through text-red-500 mr-2">$69.99</span>
              $59.99
            </p>
            <div className="flex items-center gap-4">
              <Button
                className="bg-gradient-to-r from-green-400 to-blue-500 hover:from-green-500 hover:to-blue-600 text-white"
                variant="default"
              >
                Add to Cart
              </Button>
              <Select defaultValue="1">
                <SelectTrigger className="w-16">
                  <SelectValue placeholder="Qty" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="1">1</SelectItem>
                  <SelectItem value="2">2</SelectItem>
                  <SelectItem value="3">3</SelectItem>
                  <SelectItem value="4">4</SelectItem>
                  <SelectItem value="5">5</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </div>
        <div className="card rounded overflow-hidden shadow-lg bg-gray-800">
          <Image
            alt="Durian Image"
            height="200"
            src="/products/durian.jpg"
            style={{
              aspectRatio: "200/200",
              objectFit: "cover",
              width: "100%",
            }}
            width="200"
          />
          <div className="p-4">
            <h2 className="font-bold text-xl mb-2 text-white">Durian</h2>
            <p className="text-gray-300 text-base mb-2">$79.99</p>
            <div className="flex items-center gap-4">
              <Button
                className="bg-gradient-to-r from-green-400 to-blue-500 hover:from-green-500 hover:to-blue-600 text-white"
                variant="default"
              >
                Add to Cart
              </Button>
              <Select defaultValue="1">
                <SelectTrigger className="w-16">
                  <SelectValue placeholder="Qty" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="1">1</SelectItem>
                  <SelectItem value="2">2</SelectItem>
                  <SelectItem value="3">3</SelectItem>
                  <SelectItem value="4">4</SelectItem>
                  <SelectItem value="5">5</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </div>
      </main>
      <footer className="mt-6 flex justify-center items-center">
        <nav className="flex space-x-2 text-black">
          <Button className="w-10 px-3 py-1 rounded-full" variant="outline">
            <Link aria-label="Previous Page" href="#">
                <svg
                  className=" text-white h-5 w-5"
                  fill="none"
                  height="24"
                  stroke="currentColor"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  viewBox="0 0 24 24"
                  width="24"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path d="m15 18-6-6 6-6" />
                </svg>
            </Link>
          </Button>
          <Button className="w-10 px-3 py-1 rounded-full bg-blue-500 text-white" variant="outline">
            <Link aria-label="Page 1" href="#">
                1
            </Link>
          </Button>
          <Button className="w-10 px-3 py-1 rounded-full text-white" variant="outline">
            <Link aria-label="Page 2" href="#">
                2
            </Link>
          </Button>
          <Button className="w-10 px-3 py-1 rounded-full" variant="outline">
            <Link aria-label="Next Page" href="#">
              <svg
                className=" text-white h-5 w-5"
                fill="none"
                height="24"
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                viewBox="0 0 24 24"
                width="24"
                xmlns="http://www.w3.org/2000/svg"
                >
                  <path d="m9 18 6-6-6-6" />
              </svg>
            </Link>
          </Button>
        </nav>
      </footer>
    </div>
  )
}
